
// This file has been generated by the GUI designer. Do not modify.

public partial class MainWindow
{
	private global::Gtk.VBox vbox7;

	private global::Gtk.HBox hbox2;

	private global::Gtk.Button button3;

	private global::Gtk.Button button4;

	private global::Gtk.Button button5;

	private global::Gtk.Button button6;

	private global::Gtk.Label label1;

	private global::Gtk.Image image4;

	private global::Projekt.RezervacijaWidget rezervacijawidget1;

	private global::Projekt.PregledRezervacijaWidget pregledrezervacijawidget1;

	private global::Projekt.NacionalniParkoviWidget nacionalniparkoviwidget1;

	private global::Projekt.ZaVoditeljeWidget zavoditeljewidget1;

	protected virtual void Build()
	{
		global::Stetic.Gui.Initialize(this);
		// Widget MainWindow
		this.WidthRequest = 600;
		this.HeightRequest = 400;
		this.Name = "MainWindow";
		this.Title = global::Mono.Unix.Catalog.GetString("Sustav rezervacija za nacionalne parkove RH");
		this.WindowPosition = ((global::Gtk.WindowPosition)(4));
		// Container child MainWindow.Gtk.Container+ContainerChild
		this.vbox7 = new global::Gtk.VBox();
		this.vbox7.Name = "vbox7";
		this.vbox7.Spacing = 6;
		// Container child vbox7.Gtk.Box+BoxChild
		this.hbox2 = new global::Gtk.HBox();
		this.hbox2.Name = "hbox2";
		this.hbox2.Spacing = 6;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button3 = new global::Gtk.Button();
		this.button3.WidthRequest = 135;
		this.button3.CanFocus = true;
		this.button3.Name = "button3";
		this.button3.UseUnderline = true;
		this.button3.Label = global::Mono.Unix.Catalog.GetString("Nacionalni parkovi");
		this.hbox2.Add(this.button3);
		global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button3]));
		w1.Position = 0;
		w1.Expand = false;
		w1.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button4 = new global::Gtk.Button();
		this.button4.WidthRequest = 135;
		this.button4.CanFocus = true;
		this.button4.Name = "button4";
		this.button4.UseUnderline = true;
		this.button4.Label = global::Mono.Unix.Catalog.GetString("Rezervacija");
		this.hbox2.Add(this.button4);
		global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button4]));
		w2.Position = 1;
		w2.Expand = false;
		w2.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button5 = new global::Gtk.Button();
		this.button5.WidthRequest = 135;
		this.button5.CanFocus = true;
		this.button5.Name = "button5";
		this.button5.UseUnderline = true;
		this.button5.Label = global::Mono.Unix.Catalog.GetString("Pregled rezervacija");
		this.hbox2.Add(this.button5);
		global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button5]));
		w3.Position = 2;
		w3.Expand = false;
		w3.Fill = false;
		// Container child hbox2.Gtk.Box+BoxChild
		this.button6 = new global::Gtk.Button();
		this.button6.WidthRequest = 135;
		this.button6.CanFocus = true;
		this.button6.Name = "button6";
		this.button6.UseUnderline = true;
		this.button6.Label = global::Mono.Unix.Catalog.GetString("Za voditelje");
		this.hbox2.Add(this.button6);
		global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button6]));
		w4.Position = 3;
		w4.Expand = false;
		w4.Fill = false;
		this.vbox7.Add(this.hbox2);
		global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox2]));
		w5.Position = 0;
		w5.Expand = false;
		w5.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.label1 = new global::Gtk.Label();
		this.label1.Name = "label1";
		this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Dobrodošli na sustav rezevacija za nacionalne parkove Republike Hrvatske");
		this.vbox7.Add(this.label1);
		global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label1]));
		w6.Position = 1;
		w6.Expand = false;
		w6.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.image4 = new global::Gtk.Image();
		this.image4.Name = "image4";
		this.image4.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Projekt.Images.620x349.jpg");
		this.vbox7.Add(this.image4);
		global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.image4]));
		w7.Position = 2;
		w7.Expand = false;
		w7.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.rezervacijawidget1 = new global::Projekt.RezervacijaWidget();
		this.rezervacijawidget1.Events = ((global::Gdk.EventMask)(256));
		this.rezervacijawidget1.Name = "rezervacijawidget1";
		this.vbox7.Add(this.rezervacijawidget1);
		global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.rezervacijawidget1]));
		w8.Position = 3;
		w8.Expand = false;
		w8.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.pregledrezervacijawidget1 = new global::Projekt.PregledRezervacijaWidget();
		this.pregledrezervacijawidget1.Events = ((global::Gdk.EventMask)(256));
		this.pregledrezervacijawidget1.Name = "pregledrezervacijawidget1";
		this.vbox7.Add(this.pregledrezervacijawidget1);
		global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.pregledrezervacijawidget1]));
		w9.Position = 4;
		w9.Expand = false;
		w9.Fill = false;
		// Container child vbox7.Gtk.Box+BoxChild
		this.nacionalniparkoviwidget1 = new global::Projekt.NacionalniParkoviWidget();
		this.nacionalniparkoviwidget1.Events = ((global::Gdk.EventMask)(256));
		this.nacionalniparkoviwidget1.Name = "nacionalniparkoviwidget1";
		this.vbox7.Add(this.nacionalniparkoviwidget1);
		global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.nacionalniparkoviwidget1]));
		w10.Position = 5;
		// Container child vbox7.Gtk.Box+BoxChild
		this.zavoditeljewidget1 = new global::Projekt.ZaVoditeljeWidget();
		this.zavoditeljewidget1.Events = ((global::Gdk.EventMask)(256));
		this.zavoditeljewidget1.Name = "zavoditeljewidget1";
		this.vbox7.Add(this.zavoditeljewidget1);
		global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.zavoditeljewidget1]));
		w11.Position = 6;
		w11.Expand = false;
		w11.Fill = false;
		this.Add(this.vbox7);
		if ((this.Child != null))
		{
			this.Child.ShowAll();
		}
		this.DefaultWidth = 600;
		this.DefaultHeight = 469;
		this.rezervacijawidget1.Hide();
		this.pregledrezervacijawidget1.Hide();
		this.nacionalniparkoviwidget1.Hide();
		this.zavoditeljewidget1.Hide();
		this.Show();
		this.DeleteEvent += new global::Gtk.DeleteEventHandler(this.OnDeleteEvent);
		this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		this.button4.Clicked += new global::System.EventHandler(this.OnButton4Clicked);
		this.button5.Clicked += new global::System.EventHandler(this.OnButton5Clicked);
		this.button6.Clicked += new global::System.EventHandler(this.OnButton6Clicked);
	}
}
