
// This file has been generated by the GUI designer. Do not modify.
namespace Projekt
{
	public partial class ZaVoditeljeWidgetPregledajRezervacije
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBox comboboxNP;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label4;

		private global::Gtk.ComboBox comboboxTermini;

		private global::Gtk.Button button15;

		private global::Gtk.HBox hbox3;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.NodeView nodeview1;

		private global::Gtk.Button button1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Projekt.ZaVoditeljeWidgetPregledajRezervacije
			global::Stetic.BinContainer.Attach(this);
			this.HeightRequest = 400;
			this.Name = "Projekt.ZaVoditeljeWidgetPregledajRezervacije";
			// Container child Projekt.ZaVoditeljeWidgetPregledajRezervacije.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Za voditelje");
			this.vbox7.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni park:");
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboboxNP = global::Gtk.ComboBox.NewText();
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Krka"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Risnjak"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Brijuni"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Kornati"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Sjeverni Velebit"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Paklenica"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Mljet"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Plitvička jezera"));
			this.comboboxNP.Name = "comboboxNP";
			this.hbox5.Add(this.comboboxNP);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.comboboxNP]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			this.vbox7.Add(this.hbox5);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox5]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Postojeći termini za odabrani NP:");
			this.hbox1.Add(this.label4);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label4]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.comboboxTermini = global::Gtk.ComboBox.NewText();
			this.comboboxTermini.WidthRequest = 100;
			this.comboboxTermini.Name = "comboboxTermini";
			this.hbox1.Add(this.comboboxTermini);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.comboboxTermini]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button15 = new global::Gtk.Button();
			this.button15.CanFocus = true;
			this.button15.Name = "button15";
			this.button15.UseUnderline = true;
			this.button15.Label = global::Mono.Unix.Catalog.GetString("Pregled rezervacija za termin");
			this.hbox1.Add(this.button15);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button15]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox7.Add(this.hbox1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox1]));
			w8.Position = 2;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			this.nodeview1 = new global::Gtk.NodeView();
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.GtkScrolledWindow.Add(this.nodeview1);
			this.hbox3.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.GtkScrolledWindow]));
			w10.Position = 0;
			this.vbox7.Add(this.hbox3);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox3]));
			w11.Position = 3;
			// Container child vbox7.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.WidthRequest = 100;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Povratak na izbornik za voditelje");
			this.vbox7.Add(this.button1);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.button1]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.comboboxNP.Changed += new global::System.EventHandler(this.OnComboboxNPChanged);
			this.button15.Clicked += new global::System.EventHandler(this.OnButton15Clicked);
			this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		}
	}
}
