
// This file has been generated by the GUI designer. Do not modify.
namespace Projekt
{
	public partial class RezervacijaDialog
	{
		private global::Gtk.VBox dialog1_VBox1;

		private global::Gtk.Label label3;

		private global::Gtk.Button buttonOk;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Projekt.RezervacijaDialog
			this.Name = "Projekt.RezervacijaDialog";
			this.Title = global::Mono.Unix.Catalog.GetString("Greška");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Internal child Projekt.RezervacijaDialog.VBox
			global::Gtk.VBox w1 = this.VBox;
			w1.Name = "dialog1_VBox";
			w1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox.Gtk.Box+BoxChild
			this.dialog1_VBox1 = new global::Gtk.VBox();
			this.dialog1_VBox1.Name = "dialog1_VBox1";
			this.dialog1_VBox1.BorderWidth = ((uint)(2));
			// Container child dialog1_VBox1.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.HeightRequest = 200;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Morate popuniti sva polja!\nOIB mora imati 11 znamenki, a kreditna kartica 16 znam" +
					"enki.\n\na) Kako bi mogli odabrati broj karti, trebate odabrati NP i  termin te kl" +
					"iknuti \"Provjeri cijene\".\n\nb) Broj odabranih karti ne smije biti veći od dostupn" +
					"og kapaciteta!");
			this.label3.Wrap = true;
			this.dialog1_VBox1.Add(this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.dialog1_VBox1[this.label3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			w1.Add(this.dialog1_VBox1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(w1[this.dialog1_VBox1]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Internal child Projekt.RezervacijaDialog.ActionArea
			global::Gtk.HButtonBox w4 = this.ActionArea;
			w4.Name = "dialog1_ActionArea";
			w4.Spacing = 10;
			w4.BorderWidth = ((uint)(5));
			w4.LayoutStyle = ((global::Gtk.ButtonBoxStyle)(4));
			// Container child dialog1_ActionArea.Gtk.ButtonBox+ButtonBoxChild
			this.buttonOk = new global::Gtk.Button();
			this.buttonOk.CanDefault = true;
			this.buttonOk.CanFocus = true;
			this.buttonOk.Name = "buttonOk";
			this.buttonOk.UseStock = true;
			this.buttonOk.UseUnderline = true;
			this.buttonOk.Label = "gtk-ok";
			this.AddActionWidget(this.buttonOk, -5);
			global::Gtk.ButtonBox.ButtonBoxChild w5 = ((global::Gtk.ButtonBox.ButtonBoxChild)(w4[this.buttonOk]));
			w5.Expand = false;
			w5.Fill = false;
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 413;
			this.DefaultHeight = 300;
			this.Show();
			this.buttonOk.Clicked += new global::System.EventHandler(this.OnButtonOkClicked);
		}
	}
}
