
// This file has been generated by the GUI designer. Do not modify.
namespace Projekt
{
	public partial class NacionalniParkoviWidget
	{
		private global::Gtk.VBox vbox1;

		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label1;

		private global::Gtk.ScrolledWindow GtkScrolledWindow;

		private global::Gtk.HBox hbox5;

		private global::Gtk.VBox vbox2;

		private global::Gtk.Label label2;

		private global::Gtk.Label label3;

		private global::Gtk.Label label4;

		private global::Gtk.Label label5;

		private global::Gtk.Label label8;

		private global::Gtk.Label label6;

		private global::Gtk.Label label9;

		private global::Gtk.Label label7;

		private global::Gtk.Label label10;

		private global::Gtk.Label label14;

		private global::Gtk.Label label11;

		private global::Gtk.Label label15;

		private global::Gtk.Label label12;

		private global::Gtk.Label label16;

		private global::Gtk.Label label13;

		private global::Gtk.Label label17;

		private global::Gtk.VBox vbox3;

		private global::Gtk.Image image1;

		private global::Gtk.Image image2;

		private global::Gtk.Image image3;

		private global::Gtk.Image image5;

		private global::Gtk.Image image6;

		private global::Gtk.Image image7;

		private global::Gtk.Image image9;

		private global::Gtk.Image image10;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Projekt.NacionalniParkoviWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Projekt.NacionalniParkoviWidget";
			// Container child Projekt.NacionalniParkoviWidget.Gtk.Container+ContainerChild
			this.vbox1 = new global::Gtk.VBox();
			this.vbox1.Name = "vbox1";
			this.vbox1.Spacing = 6;
			// Container child vbox1.Gtk.Box+BoxChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni parkovi");
			this.vbox7.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			this.vbox1.Add(this.vbox7);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.vbox7]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox1.Gtk.Box+BoxChild
			this.GtkScrolledWindow = new global::Gtk.ScrolledWindow();
			this.GtkScrolledWindow.Name = "GtkScrolledWindow";
			this.GtkScrolledWindow.HscrollbarPolicy = ((global::Gtk.PolicyType)(2));
			this.GtkScrolledWindow.ShadowType = ((global::Gtk.ShadowType)(1));
			// Container child GtkScrolledWindow.Gtk.Container+ContainerChild
			global::Gtk.Viewport w3 = new global::Gtk.Viewport();
			w3.ShadowType = ((global::Gtk.ShadowType)(0));
			// Container child GtkViewport.Gtk.Container+ContainerChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.WidthRequest = 270;
			this.label2.HeightRequest = 50;
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni park Risnjak ");
			this.label2.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label2);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label2]));
			w4.Position = 0;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 270;
			this.label3.HeightRequest = 150;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString(@"Iz šumskog prostranstva Gorskog kotara izdižu se dva planinska ogoljela masiva – Risnjak i Snježnik. Udaljeni jedan od drugoga samo tri kilometra, kamenim licem o lice gledaju se kao planine blizanci. U najnižim dijelovima Parka na svoj dugi riječni put kreće za mnoge najljepša hrvatska rijeka – Kupa.");
			this.label3.Wrap = true;
			this.vbox2.Add(this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label3]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 270;
			this.label4.HeightRequest = 50;
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni park Krka");
			this.label4.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label4);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label4]));
			w6.Position = 2;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.WidthRequest = 270;
			this.label5.HeightRequest = 150;
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Sedam veličanstvenih: Bilušića buk, Brljan, Manojlovac, Rošnjak, Miljacka slap, R" +
					"oški slap i Skradinski buk. To su sedreni slapovi Krke. Za mnoge, najljepše plav" +
					"e linije dalmatinskog krša. Divota kaskada i gusti, bogati zvuk života vode.");
			this.label5.Wrap = true;
			this.vbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label5]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.WidthRequest = 270;
			this.label8.HeightRequest = 50;
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni park Paklenica");
			this.label8.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label8);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label8]));
			w8.Position = 4;
			w8.Expand = false;
			w8.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 270;
			this.label6.HeightRequest = 150;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString(@"Orijaški klanci Velike i Male Paklenice ne ostavljaju mjesta ravnodušju nad malenkosti čovjeka podno planine. Snaga prirode ovdje nije sustezala svoju nadmoć, ali i dobrostivost prema onima koji je poštuju. Ovdje se nalaze najviši velebitski vrhovi. Paklenica je alpinistička izazovna poslastica. ");
			this.label6.Wrap = true;
			this.vbox2.Add(this.label6);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label6]));
			w9.Position = 5;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.WidthRequest = 270;
			this.label9.HeightRequest = 50;
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni park Kornati");
			this.label9.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label9);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label9]));
			w10.Position = 6;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.WidthRequest = 270;
			this.label7.HeightRequest = 150;
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString(@"Kameni labirint osamdeset i devet otoka, otočića i hridi u moru – to su Kornati. Najrazvedenija otočna skupina u Sredozemlju. Pogled na kornatske otoke iz zraka, s mora... ili s otočnih vidikovaca na more jednako je dojmljiv – a oku potpuno različit. Svaki je vrijedan iskustva i proučavanja. ");
			this.label7.Wrap = true;
			this.vbox2.Add(this.label7);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label7]));
			w11.Position = 7;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.WidthRequest = 270;
			this.label10.HeightRequest = 50;
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni park Mljet");
			this.label10.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label10);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label10]));
			w12.Position = 8;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.WidthRequest = 270;
			this.label14.HeightRequest = 150;
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString(@"Mljet – zeleni otok. Homerova Ogigija. Legenda kaže da je ljubavnica grčkog junaka Odiseja, nimfa Kalipsa, upravo ovaj otok izabrala za svoj dom: jedino je njegova ljepota nadmašila njezinu i tako je privoljela vječnog putnika, Odiseja, na višegodišnji ostanak. Ima li u legendi i činjenica? ");
			this.label14.Wrap = true;
			this.vbox2.Add(this.label14);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label14]));
			w13.Position = 9;
			w13.Expand = false;
			w13.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.WidthRequest = 270;
			this.label11.HeightRequest = 50;
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni park Brijuni");
			this.label11.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label11);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label11]));
			w14.Position = 10;
			w14.Expand = false;
			w14.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label();
			this.label15.WidthRequest = 270;
			this.label15.HeightRequest = 150;
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString(@"Odvajanjem od nekadašnjeg istarskog kopna, nastali su Brijunski otoci. Nigdje toliko crnike i lovora na jednom mjestu i hlada pod krošnjama drveća širokih i dvadesetak metara. Brijuni su prekrasna slika prirode koju je kultivirao čovjek za svoj najugodniji boravak u raskoši zelenila.");
			this.label15.Wrap = true;
			this.vbox2.Add(this.label15);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label15]));
			w15.Position = 11;
			w15.Expand = false;
			w15.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.WidthRequest = 270;
			this.label12.HeightRequest = 50;
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni park Plitvička jezera");
			this.label12.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label12);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label12]));
			w16.Position = 12;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label();
			this.label16.WidthRequest = 270;
			this.label16.HeightRequest = 150;
			this.label16.Name = "label16";
			this.label16.LabelProp = global::Mono.Unix.Catalog.GetString(@"Jezerski vrtovi povezani slapovima i zagrljeni gorskim šumama. Plitvička jezera – veličanstveno i dinamično lice prirode koje se neprestano transformira. Iako znanost nudi neupitan odgovor nastanka Plitvičkih jezera i sedrenih barijera, voda je u kršu uvijek za ljude imala mitska obilježja. ");
			this.label16.Wrap = true;
			this.vbox2.Add(this.label16);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label16]));
			w17.Position = 13;
			w17.Expand = false;
			w17.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.WidthRequest = 270;
			this.label13.HeightRequest = 50;
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni park Sjeverni Velebit");
			this.label13.Justify = ((global::Gtk.Justification)(2));
			this.vbox2.Add(this.label13);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label13]));
			w18.Position = 14;
			w18.Expand = false;
			w18.Fill = false;
			// Container child vbox2.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label();
			this.label17.WidthRequest = 270;
			this.label17.HeightRequest = 150;
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("„Malo je jedan život za Velebit“ – tako u nekoliko riječi ponajbolji poznavatelji" +
					" planine opisuju raskoš raznolikosti Velebita. Iako ne najviša hrvatska planina," +
					" svakako je najpoznatija. Velebit je kralježnica koja spaja sjever i jug Hrvatsk" +
					"e.");
			this.label17.Wrap = true;
			this.vbox2.Add(this.label17);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.label17]));
			w19.Position = 15;
			w19.Expand = false;
			w19.Fill = false;
			this.hbox5.Add(this.vbox2);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox2]));
			w20.Position = 0;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.vbox3 = new global::Gtk.VBox();
			this.vbox3.Name = "vbox3";
			this.vbox3.Spacing = 6;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image1 = new global::Gtk.Image();
			this.image1.HeightRequest = 200;
			this.image1.Name = "image1";
			this.image1.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Projekt.Images.280px-NP_Risnjak_-_pogled_02.jpg");
			this.vbox3.Add(this.image1);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image1]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image2 = new global::Gtk.Image();
			this.image2.HeightRequest = 200;
			this.image2.Name = "image2";
			this.image2.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Projekt.Images.Krka-waterfalls.jpg");
			this.vbox3.Add(this.image2);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image2]));
			w22.Position = 1;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image3 = new global::Gtk.Image();
			this.image3.HeightRequest = 200;
			this.image3.Name = "image3";
			this.image3.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Projekt.Images.Nationalpark_Paklenica_Schlucht.JPG");
			this.vbox3.Add(this.image3);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image3]));
			w23.Position = 2;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image5 = new global::Gtk.Image();
			this.image5.Name = "image5";
			this.image5.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Projekt.Images.kornati.jpg");
			this.vbox3.Add(this.image5);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image5]));
			w24.Position = 3;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image6 = new global::Gtk.Image();
			this.image6.Name = "image6";
			this.image6.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Projekt.Images.mljet.jpeg");
			this.vbox3.Add(this.image6);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image6]));
			w25.Position = 4;
			w25.Expand = false;
			w25.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image7 = new global::Gtk.Image();
			this.image7.Name = "image7";
			this.image7.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Projekt.Images.more-priroda-den-brijuni-chorvatsko-0-Europa.jpg");
			this.vbox3.Add(this.image7);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image7]));
			w26.Position = 5;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image9 = new global::Gtk.Image();
			this.image9.Name = "image9";
			this.image9.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Projekt.Images.plitvice.jpg");
			this.vbox3.Add(this.image9);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image9]));
			w27.Position = 6;
			w27.Expand = false;
			w27.Fill = false;
			// Container child vbox3.Gtk.Box+BoxChild
			this.image10 = new global::Gtk.Image();
			this.image10.Name = "image10";
			this.image10.Pixbuf = global::Gdk.Pixbuf.LoadFromResource("Projekt.Images.sjeverni velebit3.jpg");
			this.vbox3.Add(this.image10);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.vbox3[this.image10]));
			w28.Position = 7;
			w28.Expand = false;
			w28.Fill = false;
			this.hbox5.Add(this.vbox3);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.vbox3]));
			w29.Position = 1;
			w29.Expand = false;
			w29.Fill = false;
			w3.Add(this.hbox5);
			this.GtkScrolledWindow.Add(w3);
			this.vbox1.Add(this.GtkScrolledWindow);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.vbox1[this.GtkScrolledWindow]));
			w32.Position = 1;
			this.Add(this.vbox1);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
