
// This file has been generated by the GUI designer. Do not modify.
namespace Projekt
{
	public partial class PregledRezervacijaWidget
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry entry1;

		private global::Gtk.Button button1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.NodeView nodeview1;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label4;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label3;

		private global::Gtk.Entry entry2;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button button10;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Projekt.PregledRezervacijaWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Projekt.PregledRezervacijaWidget";
			// Container child Projekt.PregledRezervacijaWidget.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Pregled rezervacija");
			this.vbox7.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Unesite OIB:");
			this.hbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entry1 = new global::Gtk.Entry();
			this.entry1.CanFocus = true;
			this.entry1.Name = "entry1";
			this.entry1.IsEditable = true;
			this.entry1.InvisibleChar = '●';
			this.hbox1.Add(this.entry1);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entry1]));
			w3.Position = 1;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Pretraži rezervacije");
			this.hbox1.Add(this.button1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox7.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox1]));
			w5.Position = 1;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.nodeview1 = new global::Gtk.NodeView();
			this.nodeview1.HeightRequest = 200;
			this.nodeview1.CanFocus = true;
			this.nodeview1.Name = "nodeview1";
			this.hbox3.Add(this.nodeview1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.nodeview1]));
			w6.Position = 0;
			this.vbox7.Add(this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox3]));
			w7.Position = 2;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Za otkazivanje rezervacije odaberite i označite na listi rezervaciju koju želite " +
					"otkazati (siva boja)");
			this.hbox2.Add(this.label4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label4]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.vbox7.Add(this.hbox2);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox2]));
			w9.Position = 3;
			w9.Expand = false;
			w9.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Unesite broj kreditne kartice za potvrdu otkazivanja rezervacije:");
			this.hbox6.Add(this.label3);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label3]));
			w10.Position = 0;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.entry2 = new global::Gtk.Entry();
			this.entry2.CanFocus = true;
			this.entry2.Name = "entry2";
			this.entry2.IsEditable = true;
			this.entry2.InvisibleChar = '●';
			this.hbox6.Add(this.entry2);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.entry2]));
			w11.Position = 1;
			this.vbox7.Add(this.hbox6);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox6]));
			w12.Position = 4;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button10 = new global::Gtk.Button();
			this.button10.Sensitive = false;
			this.button10.CanFocus = true;
			this.button10.Name = "button10";
			this.button10.UseUnderline = true;
			this.button10.Label = global::Mono.Unix.Catalog.GetString("Otkaži");
			this.hbox7.Add(this.button10);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button10]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			this.vbox7.Add(this.hbox7);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
			w14.Position = 5;
			w14.Expand = false;
			w14.Fill = false;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
			this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
			this.button10.Clicked += new global::System.EventHandler(this.OnButton10Clicked);
		}
	}
}
