
// This file has been generated by the GUI designer. Do not modify.
namespace Projekt
{
	public partial class RezervacijaWindow2
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Button button3;

		private global::Gtk.Button button4;

		private global::Gtk.Button button5;

		private global::Gtk.Button button6;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label2;

		private global::Gtk.ComboBox combobox2PrvaKarta;

		private global::Gtk.Label label7;

		private global::Gtk.Statusbar statusbar1;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBox combobox3;

		private global::Gtk.Label label8;

		private global::Gtk.Statusbar statusbar2;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label4;

		private global::Gtk.ComboBox combobox4;

		private global::Gtk.Label label9;

		private global::Gtk.Statusbar statusbar3;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label5;

		private global::Gtk.ComboBox combobox5;

		private global::Gtk.Label label10;

		private global::Gtk.Statusbar statusbar4;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label6;

		private global::Gtk.ComboBox combobox6;

		private global::Gtk.Label label11;

		private global::Gtk.Statusbar statusbar5;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label12;

		private global::Gtk.Entry entry2KreditnaKartica;

		private global::Gtk.Button button2RezervirajKarte;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Projekt.RezervacijaWindow2
			this.Name = "Projekt.RezervacijaWindow2";
			this.Title = global::Mono.Unix.Catalog.GetString("RezervacijaWindow2");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Projekt.RezervacijaWindow2.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.WidthRequest = 600;
			this.vbox7.HeightRequest = 400;
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button();
			this.button3.WidthRequest = 135;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Nacionalni parkovi");
			this.hbox2.Add(this.button3);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button3]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button4 = new global::Gtk.Button();
			this.button4.WidthRequest = 135;
			this.button4.CanFocus = true;
			this.button4.Name = "button4";
			this.button4.UseUnderline = true;
			this.button4.Label = global::Mono.Unix.Catalog.GetString("Rezervacija");
			this.hbox2.Add(this.button4);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button4]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button5 = new global::Gtk.Button();
			this.button5.WidthRequest = 135;
			this.button5.CanFocus = true;
			this.button5.Name = "button5";
			this.button5.UseUnderline = true;
			this.button5.Label = global::Mono.Unix.Catalog.GetString("Pregled rezervacija");
			this.hbox2.Add(this.button5);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button5]));
			w3.Position = 2;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.button6 = new global::Gtk.Button();
			this.button6.WidthRequest = 135;
			this.button6.CanFocus = true;
			this.button6.Name = "button6";
			this.button6.UseUnderline = true;
			this.button6.Label = global::Mono.Unix.Catalog.GetString("Za voditelje");
			this.hbox2.Add(this.button6);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.button6]));
			w4.Position = 3;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox7.Add(this.hbox2);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox2]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Odaberite tip i količinu karti");
			this.vbox7.Add(this.label1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label1]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Karta 1:");
			this.hbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.combobox2PrvaKarta = global::Gtk.ComboBox.NewText();
			this.combobox2PrvaKarta.AppendText(global::Mono.Unix.Catalog.GetString("Odrasli"));
			this.combobox2PrvaKarta.AppendText(global::Mono.Unix.Catalog.GetString("Djeca"));
			this.combobox2PrvaKarta.Name = "combobox2PrvaKarta";
			this.hbox1.Add(this.combobox2PrvaKarta);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.combobox2PrvaKarta]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Cijena karte 1:");
			this.hbox1.Add(this.label7);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label7]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.statusbar1 = new global::Gtk.Statusbar();
			this.statusbar1.Name = "statusbar1";
			this.statusbar1.Spacing = 6;
			this.hbox1.Add(this.statusbar1);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.statusbar1]));
			w10.Position = 3;
			this.vbox7.Add(this.hbox1);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox1]));
			w11.Position = 2;
			w11.Expand = false;
			w11.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Karta 2:");
			this.hbox3.Add(this.label3);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label3]));
			w12.Position = 0;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.combobox3 = global::Gtk.ComboBox.NewText();
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("Odrasli"));
			this.combobox3.AppendText(global::Mono.Unix.Catalog.GetString("Djeca"));
			this.combobox3.AppendText("");
			this.combobox3.Name = "combobox3";
			this.combobox3.Active = 2;
			this.hbox3.Add(this.combobox3);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.combobox3]));
			w13.Position = 1;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Cijena karte 2:");
			this.hbox3.Add(this.label8);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label8]));
			w14.Position = 2;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.statusbar2 = new global::Gtk.Statusbar();
			this.statusbar2.Name = "statusbar2";
			this.statusbar2.Spacing = 6;
			this.hbox3.Add(this.statusbar2);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.statusbar2]));
			w15.Position = 3;
			this.vbox7.Add(this.hbox3);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox3]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Karta 3:");
			this.hbox4.Add(this.label4);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label4]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.combobox4 = global::Gtk.ComboBox.NewText();
			this.combobox4.AppendText(global::Mono.Unix.Catalog.GetString("Odrasli"));
			this.combobox4.AppendText(global::Mono.Unix.Catalog.GetString("Djeca"));
			this.combobox4.Name = "combobox4";
			this.hbox4.Add(this.combobox4);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.combobox4]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Cijena karte 3:");
			this.hbox4.Add(this.label9);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label9]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.statusbar3 = new global::Gtk.Statusbar();
			this.statusbar3.Name = "statusbar3";
			this.statusbar3.Spacing = 6;
			this.hbox4.Add(this.statusbar3);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.statusbar3]));
			w20.Position = 3;
			this.vbox7.Add(this.hbox4);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox4]));
			w21.Position = 4;
			w21.Expand = false;
			w21.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Karta 4 :");
			this.hbox5.Add(this.label5);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label5]));
			w22.Position = 0;
			w22.Expand = false;
			w22.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.combobox5 = global::Gtk.ComboBox.NewText();
			this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Odrasli"));
			this.combobox5.AppendText(global::Mono.Unix.Catalog.GetString("Djeca"));
			this.combobox5.Name = "combobox5";
			this.hbox5.Add(this.combobox5);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.combobox5]));
			w23.Position = 1;
			w23.Expand = false;
			w23.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Cijena karte 4:");
			this.hbox5.Add(this.label10);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label10]));
			w24.Position = 2;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.statusbar4 = new global::Gtk.Statusbar();
			this.statusbar4.Name = "statusbar4";
			this.statusbar4.Spacing = 6;
			this.hbox5.Add(this.statusbar4);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.statusbar4]));
			w25.Position = 3;
			this.vbox7.Add(this.hbox5);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox5]));
			w26.Position = 5;
			w26.Expand = false;
			w26.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Karta 5:");
			this.hbox6.Add(this.label6);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label6]));
			w27.Position = 0;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.combobox6 = global::Gtk.ComboBox.NewText();
			this.combobox6.AppendText(global::Mono.Unix.Catalog.GetString("Odrasli"));
			this.combobox6.AppendText(global::Mono.Unix.Catalog.GetString("Djeca"));
			this.combobox6.Name = "combobox6";
			this.hbox6.Add(this.combobox6);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.combobox6]));
			w28.Position = 1;
			w28.Expand = false;
			w28.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Cijena karte 5:");
			this.hbox6.Add(this.label11);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label11]));
			w29.Position = 2;
			w29.Expand = false;
			w29.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.statusbar5 = new global::Gtk.Statusbar();
			this.statusbar5.Name = "statusbar5";
			this.statusbar5.Spacing = 6;
			this.hbox6.Add(this.statusbar5);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.statusbar5]));
			w30.Position = 3;
			this.vbox7.Add(this.hbox6);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox6]));
			w31.Position = 6;
			w31.Expand = false;
			w31.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("Unesite broj kreditne kartice:");
			this.hbox7.Add(this.label12);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label12]));
			w32.Position = 0;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.entry2KreditnaKartica = new global::Gtk.Entry();
			this.entry2KreditnaKartica.CanFocus = true;
			this.entry2KreditnaKartica.Name = "entry2KreditnaKartica";
			this.entry2KreditnaKartica.IsEditable = true;
			this.entry2KreditnaKartica.InvisibleChar = '●';
			this.hbox7.Add(this.entry2KreditnaKartica);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.entry2KreditnaKartica]));
			w33.Position = 1;
			this.vbox7.Add(this.hbox7);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
			w34.Position = 7;
			w34.Expand = false;
			w34.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.button2RezervirajKarte = new global::Gtk.Button();
			this.button2RezervirajKarte.CanFocus = true;
			this.button2RezervirajKarte.Name = "button2RezervirajKarte";
			this.button2RezervirajKarte.UseUnderline = true;
			this.button2RezervirajKarte.Label = global::Mono.Unix.Catalog.GetString("Rezerviraj karte");
			this.vbox7.Add(this.button2RezervirajKarte);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.button2RezervirajKarte]));
			w35.Position = 8;
			w35.Expand = false;
			w35.Fill = false;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 400;
			this.Show();
		}
	}
}
