
// This file has been generated by the GUI designer. Do not modify.
namespace Projekt
{
	public partial class ZaVoditeljeWindow2
	{
		private global::Gtk.VBox vbox2;

		private global::Gtk.VBox vbox9;

		private global::Gtk.Label label10;

		private global::Gtk.Label label11;

		private global::Gtk.HBox hbox11;

		private global::Gtk.Button button73;

		private global::Gtk.Button button74;

		private global::Gtk.HBox hbox12;

		private global::Gtk.Button button3;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Projekt.ZaVoditeljeWindow2
			this.WidthRequest = 600;
			this.HeightRequest = 400;
			this.Name = "Projekt.ZaVoditeljeWindow2";
			this.Title = global::Mono.Unix.Catalog.GetString("Sustav rezervacija za nacionalne parkove RH");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			// Container child Projekt.ZaVoditeljeWindow2.Gtk.Container+ContainerChild
			this.vbox2 = new global::Gtk.VBox();
			this.vbox2.Name = "vbox2";
			this.vbox2.Spacing = 6;
			// Container child vbox2.Gtk.Box+BoxChild
			this.vbox9 = new global::Gtk.VBox();
			this.vbox9.WidthRequest = 600;
			this.vbox9.HeightRequest = 400;
			this.vbox9.Name = "vbox9";
			this.vbox9.Spacing = 6;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("Za voditelje");
			this.vbox9.Add(this.label10);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label10]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.HeightRequest = 100;
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("Izbornik mogućnosti");
			this.vbox9.Add(this.label11);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.label11]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox11 = new global::Gtk.HBox();
			this.hbox11.Name = "hbox11";
			this.hbox11.Homogeneous = true;
			this.hbox11.Spacing = 6;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button73 = new global::Gtk.Button();
			this.button73.WidthRequest = 200;
			this.button73.CanFocus = true;
			this.button73.Name = "button73";
			this.button73.UseUnderline = true;
			this.button73.Label = global::Mono.Unix.Catalog.GetString("Pregled rezervacija za termin");
			this.hbox11.Add(this.button73);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button73]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox11.Gtk.Box+BoxChild
			this.button74 = new global::Gtk.Button();
			this.button74.WidthRequest = 200;
			this.button74.CanFocus = true;
			this.button74.Name = "button74";
			this.button74.UseUnderline = true;
			this.button74.Label = global::Mono.Unix.Catalog.GetString("Dodavanje termina");
			this.hbox11.Add(this.button74);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox11[this.button74]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox9.Add(this.hbox11);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox11]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox9.Gtk.Box+BoxChild
			this.hbox12 = new global::Gtk.HBox();
			this.hbox12.Name = "hbox12";
			this.hbox12.Homogeneous = true;
			this.hbox12.Spacing = 6;
			// Container child hbox12.Gtk.Box+BoxChild
			this.button3 = new global::Gtk.Button();
			this.button3.WidthRequest = 100;
			this.button3.CanFocus = true;
			this.button3.Name = "button3";
			this.button3.UseUnderline = true;
			this.button3.Label = global::Mono.Unix.Catalog.GetString("Odjava");
			this.hbox12.Add(this.button3);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox12[this.button3]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox9.Add(this.hbox12);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox9[this.hbox12]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			this.vbox2.Add(this.vbox9);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.vbox2[this.vbox9]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			this.Add(this.vbox2);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 400;
			this.Show();
			this.button73.Clicked += new global::System.EventHandler(this.OnButton73Clicked);
			this.button74.Clicked += new global::System.EventHandler(this.OnButton74Clicked);
			this.button3.Clicked += new global::System.EventHandler(this.OnButton3Clicked);
		}
	}
}
