
// This file has been generated by the GUI designer. Do not modify.
namespace Projekt
{
	public partial class ZaVoditeljeWidgetIzbornik
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label1;

		private global::Gtk.Label label3;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button button73;

		private global::Gtk.Button button74;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Button button1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Projekt.ZaVoditeljeWidgetIzbornik
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Projekt.ZaVoditeljeWidgetIzbornik";
			// Container child Projekt.ZaVoditeljeWidgetIzbornik.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.WidthRequest = 600;
			this.vbox7.HeightRequest = 400;
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Za voditelje");
			this.vbox7.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.HeightRequest = 100;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Izbornik mogućnosti");
			this.vbox7.Add(this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label3]));
			w2.Position = 1;
			w2.Expand = false;
			w2.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button73 = new global::Gtk.Button();
			this.button73.WidthRequest = 200;
			this.button73.CanFocus = true;
			this.button73.Name = "button73";
			this.button73.UseUnderline = true;
			this.button73.Label = global::Mono.Unix.Catalog.GetString("Pregled rezervacija za termin");
			this.hbox1.Add(this.button73);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button73]));
			w3.Position = 0;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button74 = new global::Gtk.Button();
			this.button74.WidthRequest = 200;
			this.button74.CanFocus = true;
			this.button74.Name = "button74";
			this.button74.UseUnderline = true;
			this.button74.Label = global::Mono.Unix.Catalog.GetString("Dodavanje termina");
			this.hbox1.Add(this.button74);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button74]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			this.vbox7.Add(this.hbox1);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox1]));
			w5.Position = 2;
			w5.Expand = false;
			w5.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Homogeneous = true;
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.WidthRequest = 100;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Odjava");
			this.hbox9.Add(this.button1);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.button1]));
			w6.Position = 0;
			w6.Expand = false;
			w6.Fill = false;
			this.vbox7.Add(this.hbox9);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox9]));
			w7.Position = 3;
			w7.Expand = false;
			w7.Fill = false;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.Hide();
		}
	}
}
