
// This file has been generated by the GUI designer. Do not modify.
namespace Projekt
{
	public partial class RezervacijaWidget
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Label label2;

		private global::Gtk.Entry entryOIB;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label3;

		private global::Gtk.Entry entryIme;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Label label4;

		private global::Gtk.Entry entryPrezime;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label5;

		private global::Gtk.ComboBox comboboxNP;

		private global::Gtk.Label label15;

		private global::Gtk.Label label16;

		private global::Gtk.Label label17;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label6;

		private global::Gtk.ComboBox comboboxTermini;

		private global::Gtk.Button buttonPROVJERICIJENE;

		private global::Gtk.Label label11;

		private global::Gtk.Label label18;

		private global::Gtk.Label label13;

		private global::Gtk.HBox hbox8;

		private global::Gtk.Label label7;

		private global::Gtk.ComboBox comboboxDjeca;

		private global::Gtk.Label label12;

		private global::Gtk.Label label19;

		private global::Gtk.Label label14;

		private global::Gtk.HBox hbox9;

		private global::Gtk.Label label8;

		private global::Gtk.ComboBox comboboxOdrasli;

		private global::Gtk.Label label10;

		private global::Gtk.Label label20;

		private global::Gtk.Label label21;

		private global::Gtk.HBox hbox10;

		private global::Gtk.Label label9;

		private global::Gtk.Entry entryKreditnaKartica;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Button button1NastaviRezervaciju;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Projekt.RezervacijaWidget
			global::Stetic.BinContainer.Attach(this);
			this.Name = "Projekt.RezervacijaWidget";
			// Container child Projekt.RezervacijaWidget.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.WidthRequest = 600;
			this.vbox7.HeightRequest = 400;
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Rezervacija");
			this.vbox7.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.WidthRequest = 0;
			this.hbox1.Name = "hbox1";
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.WidthRequest = 75;
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("OIB:");
			this.hbox1.Add(this.label2);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.label2]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.entryOIB = new global::Gtk.Entry();
			this.entryOIB.WidthRequest = 1;
			this.entryOIB.CanFocus = true;
			this.entryOIB.Name = "entryOIB";
			this.entryOIB.IsEditable = true;
			this.entryOIB.InvisibleChar = '●';
			this.hbox1.Add(this.entryOIB);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.entryOIB]));
			w3.Position = 1;
			this.vbox7.Add(this.hbox1);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox1]));
			w4.Position = 1;
			w4.Expand = false;
			w4.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 75;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Ime:");
			this.hbox3.Add(this.label3);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label3]));
			w5.Position = 0;
			w5.Expand = false;
			w5.Fill = false;
			// Container child hbox3.Gtk.Box+BoxChild
			this.entryIme = new global::Gtk.Entry();
			this.entryIme.CanFocus = true;
			this.entryIme.Name = "entryIme";
			this.entryIme.IsEditable = true;
			this.entryIme.InvisibleChar = '●';
			this.hbox3.Add(this.entryIme);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.entryIme]));
			w6.Position = 1;
			this.vbox7.Add(this.hbox3);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox3]));
			w7.Position = 2;
			w7.Expand = false;
			w7.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.WidthRequest = 75;
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("Prezime:");
			this.hbox4.Add(this.label4);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.label4]));
			w8.Position = 0;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox4.Gtk.Box+BoxChild
			this.entryPrezime = new global::Gtk.Entry();
			this.entryPrezime.CanFocus = true;
			this.entryPrezime.Name = "entryPrezime";
			this.entryPrezime.IsEditable = true;
			this.entryPrezime.InvisibleChar = '●';
			this.hbox4.Add(this.entryPrezime);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.entryPrezime]));
			w9.Position = 1;
			this.vbox7.Add(this.hbox4);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox4]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.WidthRequest = 75;
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Destinacija:");
			this.hbox5.Add(this.label5);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label5]));
			w11.Position = 0;
			w11.Expand = false;
			w11.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboboxNP = global::Gtk.ComboBox.NewText();
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Krka"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Risnjak"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Brijuni"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Kornati"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Sjeverni Velebit"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Paklenica"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Mljet"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Plitvička jezera"));
			this.comboboxNP.WidthRequest = 125;
			this.comboboxNP.Name = "comboboxNP";
			this.hbox5.Add(this.comboboxNP);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.comboboxNP]));
			w12.Position = 1;
			w12.Expand = false;
			w12.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label15 = new global::Gtk.Label();
			this.label15.Name = "label15";
			this.label15.LabelProp = global::Mono.Unix.Catalog.GetString("                                     Kapacitet (ne smije biti negativan):");
			this.hbox5.Add(this.label15);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label15]));
			w13.Position = 2;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label16 = new global::Gtk.Label();
			this.label16.WidthRequest = 40;
			this.label16.Name = "label16";
			this.hbox5.Add(this.label16);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label16]));
			w14.Position = 3;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label17 = new global::Gtk.Label();
			this.label17.Name = "label17";
			this.label17.LabelProp = global::Mono.Unix.Catalog.GetString("mjesta");
			this.hbox5.Add(this.label17);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label17]));
			w15.Position = 4;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox7.Add(this.hbox5);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox5]));
			w16.Position = 4;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 75;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Termini:");
			this.hbox6.Add(this.label6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.comboboxTermini = global::Gtk.ComboBox.NewText();
			this.comboboxTermini.WidthRequest = 125;
			this.comboboxTermini.Name = "comboboxTermini";
			this.hbox6.Add(this.comboboxTermini);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.comboboxTermini]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.buttonPROVJERICIJENE = new global::Gtk.Button();
			this.buttonPROVJERICIJENE.CanFocus = true;
			this.buttonPROVJERICIJENE.Name = "buttonPROVJERICIJENE";
			this.buttonPROVJERICIJENE.UseUnderline = true;
			this.buttonPROVJERICIJENE.Label = global::Mono.Unix.Catalog.GetString("Provjeri cijene");
			this.hbox6.Add(this.buttonPROVJERICIJENE);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.buttonPROVJERICIJENE]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("                               Cijena karte za djecu:");
			this.hbox6.Add(this.label11);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label11]));
			w20.Position = 3;
			w20.Expand = false;
			w20.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label18 = new global::Gtk.Label();
			this.label18.WidthRequest = 40;
			this.label18.Name = "label18";
			this.hbox6.Add(this.label18);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label18]));
			w21.Position = 4;
			w21.Expand = false;
			w21.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label13 = new global::Gtk.Label();
			this.label13.Name = "label13";
			this.label13.LabelProp = global::Mono.Unix.Catalog.GetString("kn  ");
			this.hbox6.Add(this.label13);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label13]));
			w22.Position = 5;
			w22.Expand = false;
			w22.Fill = false;
			this.vbox7.Add(this.hbox6);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox6]));
			w23.Position = 5;
			w23.Expand = false;
			w23.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox8 = new global::Gtk.HBox();
			this.hbox8.Name = "hbox8";
			this.hbox8.Spacing = 6;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.WidthRequest = 75;
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("Dječje karte:");
			this.hbox8.Add(this.label7);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label7]));
			w24.Position = 0;
			w24.Expand = false;
			w24.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.comboboxDjeca = global::Gtk.ComboBox.NewText();
			this.comboboxDjeca.AppendText(global::Mono.Unix.Catalog.GetString("0"));
			this.comboboxDjeca.AppendText(global::Mono.Unix.Catalog.GetString("1"));
			this.comboboxDjeca.AppendText(global::Mono.Unix.Catalog.GetString("2"));
			this.comboboxDjeca.AppendText(global::Mono.Unix.Catalog.GetString("3"));
			this.comboboxDjeca.AppendText(global::Mono.Unix.Catalog.GetString("4"));
			this.comboboxDjeca.AppendText(global::Mono.Unix.Catalog.GetString("5"));
			this.comboboxDjeca.WidthRequest = 125;
			this.comboboxDjeca.Sensitive = false;
			this.comboboxDjeca.Name = "comboboxDjeca";
			this.comboboxDjeca.Active = 0;
			this.hbox8.Add(this.comboboxDjeca);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.comboboxDjeca]));
			w25.Position = 1;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label12 = new global::Gtk.Label();
			this.label12.Name = "label12";
			this.label12.LabelProp = global::Mono.Unix.Catalog.GetString("                                                          Cijena karte za odrasle" +
					":");
			this.hbox8.Add(this.label12);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label12]));
			w26.Position = 2;
			w26.Expand = false;
			w26.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label19 = new global::Gtk.Label();
			this.label19.WidthRequest = 40;
			this.label19.Name = "label19";
			this.hbox8.Add(this.label19);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label19]));
			w27.Position = 3;
			w27.Expand = false;
			w27.Fill = false;
			// Container child hbox8.Gtk.Box+BoxChild
			this.label14 = new global::Gtk.Label();
			this.label14.Name = "label14";
			this.label14.LabelProp = global::Mono.Unix.Catalog.GetString("kn  ");
			this.hbox8.Add(this.label14);
			global::Gtk.Box.BoxChild w28 = ((global::Gtk.Box.BoxChild)(this.hbox8[this.label14]));
			w28.Position = 4;
			w28.Expand = false;
			w28.Fill = false;
			this.vbox7.Add(this.hbox8);
			global::Gtk.Box.BoxChild w29 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox8]));
			w29.Position = 6;
			w29.Expand = false;
			w29.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox9 = new global::Gtk.HBox();
			this.hbox9.Name = "hbox9";
			this.hbox9.Spacing = 6;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.WidthRequest = 75;
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Odrasle karte:");
			this.hbox9.Add(this.label8);
			global::Gtk.Box.BoxChild w30 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label8]));
			w30.Position = 0;
			w30.Expand = false;
			w30.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.comboboxOdrasli = global::Gtk.ComboBox.NewText();
			this.comboboxOdrasli.AppendText(global::Mono.Unix.Catalog.GetString("0"));
			this.comboboxOdrasli.AppendText(global::Mono.Unix.Catalog.GetString("1"));
			this.comboboxOdrasli.AppendText(global::Mono.Unix.Catalog.GetString("2"));
			this.comboboxOdrasli.AppendText(global::Mono.Unix.Catalog.GetString("3"));
			this.comboboxOdrasli.AppendText(global::Mono.Unix.Catalog.GetString("4"));
			this.comboboxOdrasli.AppendText(global::Mono.Unix.Catalog.GetString("5"));
			this.comboboxOdrasli.WidthRequest = 125;
			this.comboboxOdrasli.Sensitive = false;
			this.comboboxOdrasli.Name = "comboboxOdrasli";
			this.comboboxOdrasli.Active = 0;
			this.hbox9.Add(this.comboboxOdrasli);
			global::Gtk.Box.BoxChild w31 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.comboboxOdrasli]));
			w31.Position = 1;
			w31.Expand = false;
			w31.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.WidthRequest = 294;
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("                                                                        Ukupna ci" +
					"jena:");
			this.label10.Justify = ((global::Gtk.Justification)(2));
			this.hbox9.Add(this.label10);
			global::Gtk.Box.BoxChild w32 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label10]));
			w32.Position = 2;
			w32.Expand = false;
			w32.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label20 = new global::Gtk.Label();
			this.label20.WidthRequest = 40;
			this.label20.Name = "label20";
			this.hbox9.Add(this.label20);
			global::Gtk.Box.BoxChild w33 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label20]));
			w33.Position = 3;
			w33.Expand = false;
			w33.Fill = false;
			// Container child hbox9.Gtk.Box+BoxChild
			this.label21 = new global::Gtk.Label();
			this.label21.Name = "label21";
			this.label21.LabelProp = global::Mono.Unix.Catalog.GetString("kn");
			this.hbox9.Add(this.label21);
			global::Gtk.Box.BoxChild w34 = ((global::Gtk.Box.BoxChild)(this.hbox9[this.label21]));
			w34.Position = 4;
			w34.Expand = false;
			w34.Fill = false;
			this.vbox7.Add(this.hbox9);
			global::Gtk.Box.BoxChild w35 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox9]));
			w35.Position = 7;
			w35.Expand = false;
			w35.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox10 = new global::Gtk.HBox();
			this.hbox10.Name = "hbox10";
			this.hbox10.Spacing = 6;
			// Container child hbox10.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.WidthRequest = 75;
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("Broj kreditne kartice:");
			this.label9.Wrap = true;
			this.hbox10.Add(this.label9);
			global::Gtk.Box.BoxChild w36 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.label9]));
			w36.Position = 0;
			w36.Expand = false;
			w36.Fill = false;
			// Container child hbox10.Gtk.Box+BoxChild
			this.entryKreditnaKartica = new global::Gtk.Entry();
			this.entryKreditnaKartica.WidthRequest = 1;
			this.entryKreditnaKartica.CanFocus = true;
			this.entryKreditnaKartica.Name = "entryKreditnaKartica";
			this.entryKreditnaKartica.IsEditable = true;
			this.entryKreditnaKartica.InvisibleChar = '●';
			this.hbox10.Add(this.entryKreditnaKartica);
			global::Gtk.Box.BoxChild w37 = ((global::Gtk.Box.BoxChild)(this.hbox10[this.entryKreditnaKartica]));
			w37.Position = 1;
			this.vbox7.Add(this.hbox10);
			global::Gtk.Box.BoxChild w38 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox10]));
			w38.Position = 8;
			w38.Expand = false;
			w38.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.button1NastaviRezervaciju = new global::Gtk.Button();
			this.button1NastaviRezervaciju.WidthRequest = 100;
			this.button1NastaviRezervaciju.Sensitive = false;
			this.button1NastaviRezervaciju.CanFocus = true;
			this.button1NastaviRezervaciju.Name = "button1NastaviRezervaciju";
			this.button1NastaviRezervaciju.UseUnderline = true;
			this.button1NastaviRezervaciju.Label = global::Mono.Unix.Catalog.GetString("Rezerviraj");
			this.hbox7.Add(this.button1NastaviRezervaciju);
			global::Gtk.Box.BoxChild w39 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.button1NastaviRezervaciju]));
			w39.Position = 0;
			w39.Expand = false;
			w39.Fill = false;
			this.vbox7.Add(this.hbox7);
			global::Gtk.Box.BoxChild w40 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
			w40.Position = 9;
			w40.Expand = false;
			w40.Fill = false;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.vbox7.Hide();
			this.Hide();
			this.comboboxNP.Changed += new global::System.EventHandler(this.OnComboboxNPChanged);
			this.comboboxTermini.Changed += new global::System.EventHandler(this.OnComboboxTerminiChanged);
			this.buttonPROVJERICIJENE.Clicked += new global::System.EventHandler(this.OnButtonPROVJERICIJENEClicked);
			this.comboboxDjeca.Changed += new global::System.EventHandler(this.OnComboboxDjecaChanged);
			this.comboboxOdrasli.Changed += new global::System.EventHandler(this.OnComboboxOdrasliChanged);
			this.button1NastaviRezervaciju.Clicked += new global::System.EventHandler(this.OnButton1NastaviRezervacijuClicked);
		}
	}
}
