
// This file has been generated by the GUI designer. Do not modify.
namespace Projekt
{
	public partial class ZavoditeljeWindow3
	{
		private global::Gtk.VBox vbox7;

		private global::Gtk.Label label1;

		private global::Gtk.HBox hbox5;

		private global::Gtk.Label label3;

		private global::Gtk.ComboBox comboboxNP;

		private global::Gtk.Label label4;

		private global::Gtk.ComboBox comboboxTermini;

		private global::Gtk.HBox hbox2;

		private global::Gtk.Label label5;

		private global::Gtk.SpinButton spinbutton1;

		private global::Gtk.Label label9;

		private global::Gtk.Label label7;

		private global::Gtk.Button buttonIzbrisi;

		private global::Gtk.HBox hbox7;

		private global::Gtk.Label label8;

		private global::Gtk.SpinButton spinbutton3;

		private global::Gtk.Label label10;

		private global::Gtk.HBox hbox6;

		private global::Gtk.Label label6;

		private global::Gtk.SpinButton spinbutton2;

		private global::Gtk.Label label11;

		private global::Gtk.HBox hbox3;

		private global::Gtk.Label label2;

		private global::Gtk.HBox hbox4;

		private global::Gtk.Calendar calendar1;

		private global::Gtk.HBox hbox1;

		private global::Gtk.Button button225;

		private global::Gtk.Button button1;

		protected virtual void Build()
		{
			global::Stetic.Gui.Initialize(this);
			// Widget Projekt.ZavoditeljeWindow3
			this.WidthRequest = 600;
			this.HeightRequest = 450;
			this.Name = "Projekt.ZavoditeljeWindow3";
			this.Title = global::Mono.Unix.Catalog.GetString("Sustav rezervacija za nacionalne parkove RH");
			this.WindowPosition = ((global::Gtk.WindowPosition)(4));
			this.Modal = true;
			// Container child Projekt.ZavoditeljeWindow3.Gtk.Container+ContainerChild
			this.vbox7 = new global::Gtk.VBox();
			this.vbox7.WidthRequest = 600;
			this.vbox7.HeightRequest = 400;
			this.vbox7.Name = "vbox7";
			this.vbox7.Spacing = 6;
			// Container child vbox7.Gtk.Box+BoxChild
			this.label1 = new global::Gtk.Label();
			this.label1.Name = "label1";
			this.label1.LabelProp = global::Mono.Unix.Catalog.GetString("Za voditelje");
			this.vbox7.Add(this.label1);
			global::Gtk.Box.BoxChild w1 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.label1]));
			w1.Position = 0;
			w1.Expand = false;
			w1.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox5 = new global::Gtk.HBox();
			this.hbox5.Name = "hbox5";
			this.hbox5.Spacing = 6;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label3 = new global::Gtk.Label();
			this.label3.WidthRequest = 100;
			this.label3.Name = "label3";
			this.label3.LabelProp = global::Mono.Unix.Catalog.GetString("Nacionalni park:");
			this.hbox5.Add(this.label3);
			global::Gtk.Box.BoxChild w2 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label3]));
			w2.Position = 0;
			w2.Expand = false;
			w2.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboboxNP = global::Gtk.ComboBox.NewText();
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Krka"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Risnjak"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Brijuni"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Kornati"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Sjeverni Velebit"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Paklenica"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Mljet"));
			this.comboboxNP.AppendText(global::Mono.Unix.Catalog.GetString("Plitvička jezera"));
			this.comboboxNP.Name = "comboboxNP";
			this.hbox5.Add(this.comboboxNP);
			global::Gtk.Box.BoxChild w3 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.comboboxNP]));
			w3.Position = 1;
			w3.Expand = false;
			w3.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.label4 = new global::Gtk.Label();
			this.label4.Name = "label4";
			this.label4.LabelProp = global::Mono.Unix.Catalog.GetString("                                                Postojeći termini:");
			this.hbox5.Add(this.label4);
			global::Gtk.Box.BoxChild w4 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.label4]));
			w4.Position = 2;
			w4.Expand = false;
			w4.Fill = false;
			// Container child hbox5.Gtk.Box+BoxChild
			this.comboboxTermini = global::Gtk.ComboBox.NewText();
			this.comboboxTermini.WidthRequest = 100;
			this.comboboxTermini.Name = "comboboxTermini";
			this.hbox5.Add(this.comboboxTermini);
			global::Gtk.Box.BoxChild w5 = ((global::Gtk.Box.BoxChild)(this.hbox5[this.comboboxTermini]));
			w5.Position = 3;
			w5.Expand = false;
			w5.Fill = false;
			this.vbox7.Add(this.hbox5);
			global::Gtk.Box.BoxChild w6 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox5]));
			w6.Position = 1;
			w6.Expand = false;
			w6.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox2 = new global::Gtk.HBox();
			this.hbox2.Name = "hbox2";
			this.hbox2.Spacing = 6;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label5 = new global::Gtk.Label();
			this.label5.WidthRequest = 100;
			this.label5.Name = "label5";
			this.label5.LabelProp = global::Mono.Unix.Catalog.GetString("Cijena - Djeca:");
			this.hbox2.Add(this.label5);
			global::Gtk.Box.BoxChild w7 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label5]));
			w7.Position = 0;
			w7.Expand = false;
			w7.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.spinbutton1 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinbutton1.CanFocus = true;
			this.spinbutton1.Name = "spinbutton1";
			this.spinbutton1.Adjustment.PageIncrement = 10D;
			this.spinbutton1.ClimbRate = 1D;
			this.spinbutton1.Numeric = true;
			this.hbox2.Add(this.spinbutton1);
			global::Gtk.Box.BoxChild w8 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.spinbutton1]));
			w8.Position = 1;
			w8.Expand = false;
			w8.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label9 = new global::Gtk.Label();
			this.label9.Name = "label9";
			this.label9.LabelProp = global::Mono.Unix.Catalog.GetString("kn");
			this.hbox2.Add(this.label9);
			global::Gtk.Box.BoxChild w9 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label9]));
			w9.Position = 2;
			w9.Expand = false;
			w9.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.label7 = new global::Gtk.Label();
			this.label7.WidthRequest = 290;
			this.label7.Name = "label7";
			this.label7.LabelProp = global::Mono.Unix.Catalog.GetString("          Ako termin nema rezervacija, može ga se izbrisati:");
			this.label7.Justify = ((global::Gtk.Justification)(1));
			this.hbox2.Add(this.label7);
			global::Gtk.Box.BoxChild w10 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.label7]));
			w10.Position = 3;
			w10.Expand = false;
			w10.Fill = false;
			// Container child hbox2.Gtk.Box+BoxChild
			this.buttonIzbrisi = new global::Gtk.Button();
			this.buttonIzbrisi.WidthRequest = 100;
			this.buttonIzbrisi.Sensitive = false;
			this.buttonIzbrisi.CanFocus = true;
			this.buttonIzbrisi.Name = "buttonIzbrisi";
			this.buttonIzbrisi.UseUnderline = true;
			this.buttonIzbrisi.Label = global::Mono.Unix.Catalog.GetString("Izbriši termin");
			this.hbox2.Add(this.buttonIzbrisi);
			global::Gtk.Box.BoxChild w11 = ((global::Gtk.Box.BoxChild)(this.hbox2[this.buttonIzbrisi]));
			w11.Position = 4;
			w11.Expand = false;
			w11.Fill = false;
			this.vbox7.Add(this.hbox2);
			global::Gtk.Box.BoxChild w12 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox2]));
			w12.Position = 2;
			w12.Expand = false;
			w12.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox7 = new global::Gtk.HBox();
			this.hbox7.Name = "hbox7";
			this.hbox7.Spacing = 6;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label8 = new global::Gtk.Label();
			this.label8.WidthRequest = 100;
			this.label8.Name = "label8";
			this.label8.LabelProp = global::Mono.Unix.Catalog.GetString("Cijena - Odrasli:");
			this.hbox7.Add(this.label8);
			global::Gtk.Box.BoxChild w13 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label8]));
			w13.Position = 0;
			w13.Expand = false;
			w13.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.spinbutton3 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinbutton3.CanFocus = true;
			this.spinbutton3.Name = "spinbutton3";
			this.spinbutton3.Adjustment.PageIncrement = 10D;
			this.spinbutton3.ClimbRate = 1D;
			this.spinbutton3.Numeric = true;
			this.hbox7.Add(this.spinbutton3);
			global::Gtk.Box.BoxChild w14 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.spinbutton3]));
			w14.Position = 1;
			w14.Expand = false;
			w14.Fill = false;
			// Container child hbox7.Gtk.Box+BoxChild
			this.label10 = new global::Gtk.Label();
			this.label10.Name = "label10";
			this.label10.LabelProp = global::Mono.Unix.Catalog.GetString("kn");
			this.hbox7.Add(this.label10);
			global::Gtk.Box.BoxChild w15 = ((global::Gtk.Box.BoxChild)(this.hbox7[this.label10]));
			w15.Position = 2;
			w15.Expand = false;
			w15.Fill = false;
			this.vbox7.Add(this.hbox7);
			global::Gtk.Box.BoxChild w16 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox7]));
			w16.Position = 3;
			w16.Expand = false;
			w16.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox6 = new global::Gtk.HBox();
			this.hbox6.Name = "hbox6";
			this.hbox6.Spacing = 6;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label6 = new global::Gtk.Label();
			this.label6.WidthRequest = 100;
			this.label6.Name = "label6";
			this.label6.LabelProp = global::Mono.Unix.Catalog.GetString("Kapacitet:");
			this.hbox6.Add(this.label6);
			global::Gtk.Box.BoxChild w17 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label6]));
			w17.Position = 0;
			w17.Expand = false;
			w17.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.spinbutton2 = new global::Gtk.SpinButton(0D, 100D, 1D);
			this.spinbutton2.CanFocus = true;
			this.spinbutton2.Name = "spinbutton2";
			this.spinbutton2.Adjustment.PageIncrement = 10D;
			this.spinbutton2.ClimbRate = 1D;
			this.spinbutton2.Numeric = true;
			this.hbox6.Add(this.spinbutton2);
			global::Gtk.Box.BoxChild w18 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.spinbutton2]));
			w18.Position = 1;
			w18.Expand = false;
			w18.Fill = false;
			// Container child hbox6.Gtk.Box+BoxChild
			this.label11 = new global::Gtk.Label();
			this.label11.Name = "label11";
			this.label11.LabelProp = global::Mono.Unix.Catalog.GetString("mjesta");
			this.hbox6.Add(this.label11);
			global::Gtk.Box.BoxChild w19 = ((global::Gtk.Box.BoxChild)(this.hbox6[this.label11]));
			w19.Position = 2;
			w19.Expand = false;
			w19.Fill = false;
			this.vbox7.Add(this.hbox6);
			global::Gtk.Box.BoxChild w20 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox6]));
			w20.Position = 4;
			w20.Expand = false;
			w20.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox3 = new global::Gtk.HBox();
			this.hbox3.Name = "hbox3";
			this.hbox3.Homogeneous = true;
			this.hbox3.Spacing = 6;
			// Container child hbox3.Gtk.Box+BoxChild
			this.label2 = new global::Gtk.Label();
			this.label2.Name = "label2";
			this.label2.LabelProp = global::Mono.Unix.Catalog.GetString("Unesite datum termina:");
			this.hbox3.Add(this.label2);
			global::Gtk.Box.BoxChild w21 = ((global::Gtk.Box.BoxChild)(this.hbox3[this.label2]));
			w21.Position = 0;
			w21.Expand = false;
			w21.Fill = false;
			this.vbox7.Add(this.hbox3);
			global::Gtk.Box.BoxChild w22 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox3]));
			w22.Position = 5;
			w22.Expand = false;
			w22.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox4 = new global::Gtk.HBox();
			this.hbox4.Name = "hbox4";
			this.hbox4.Homogeneous = true;
			this.hbox4.Spacing = 6;
			// Container child hbox4.Gtk.Box+BoxChild
			this.calendar1 = new global::Gtk.Calendar();
			this.calendar1.CanFocus = true;
			this.calendar1.Name = "calendar1";
			this.calendar1.DisplayOptions = ((global::Gtk.CalendarDisplayOptions)(35));
			this.hbox4.Add(this.calendar1);
			global::Gtk.Box.BoxChild w23 = ((global::Gtk.Box.BoxChild)(this.hbox4[this.calendar1]));
			w23.Position = 0;
			w23.Expand = false;
			w23.Fill = false;
			this.vbox7.Add(this.hbox4);
			global::Gtk.Box.BoxChild w24 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox4]));
			w24.Position = 6;
			w24.Expand = false;
			w24.Fill = false;
			// Container child vbox7.Gtk.Box+BoxChild
			this.hbox1 = new global::Gtk.HBox();
			this.hbox1.Name = "hbox1";
			this.hbox1.Homogeneous = true;
			this.hbox1.Spacing = 6;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button225 = new global::Gtk.Button();
			this.button225.WidthRequest = 200;
			this.button225.CanFocus = true;
			this.button225.Name = "button225";
			this.button225.UseUnderline = true;
			this.button225.Label = global::Mono.Unix.Catalog.GetString("Dodaj termin");
			this.hbox1.Add(this.button225);
			global::Gtk.Box.BoxChild w25 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button225]));
			w25.Position = 0;
			w25.Expand = false;
			w25.Fill = false;
			// Container child hbox1.Gtk.Box+BoxChild
			this.button1 = new global::Gtk.Button();
			this.button1.WidthRequest = 200;
			this.button1.CanFocus = true;
			this.button1.Name = "button1";
			this.button1.UseUnderline = true;
			this.button1.Label = global::Mono.Unix.Catalog.GetString("Povratak na izbornik za voditelje");
			this.hbox1.Add(this.button1);
			global::Gtk.Box.BoxChild w26 = ((global::Gtk.Box.BoxChild)(this.hbox1[this.button1]));
			w26.Position = 1;
			w26.Expand = false;
			w26.Fill = false;
			this.vbox7.Add(this.hbox1);
			global::Gtk.Box.BoxChild w27 = ((global::Gtk.Box.BoxChild)(this.vbox7[this.hbox1]));
			w27.Position = 7;
			w27.Expand = false;
			w27.Fill = false;
			this.Add(this.vbox7);
			if ((this.Child != null))
			{
				this.Child.ShowAll();
			}
			this.DefaultWidth = 600;
			this.DefaultHeight = 450;
			this.Show();
			this.comboboxNP.Changed += new global::System.EventHandler(this.OnComboboxNPChanged);
			this.comboboxTermini.Changed += new global::System.EventHandler(this.OnComboboxTerminiChanged);
			this.buttonIzbrisi.Clicked += new global::System.EventHandler(this.OnButtonIzbrisiClicked);
			this.button225.Clicked += new global::System.EventHandler(this.OnButton225Clicked);
			this.button1.Clicked += new global::System.EventHandler(this.OnButton1Clicked);
		}
	}
}
